import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AlertTriangle, ArrowUpRight, CalendarDays, Check, ChevronDown, ClipboardList, CloudSun, Compass, ExternalLink, FileCheck2, Hotel as HotelIcon, Info, Landmark, ListChecks, Map, Plane, RotateCcw, ShieldCheck, ShoppingBag, WalletCards, Waves, X } from 'lucide-react'
import { trip, tripStatus } from './data/trip'
import { flights } from './data/flights'
import { hotels } from './data/hotels'
import { itinerary } from './data/itinerary'
import { checklistGroups } from './data/checklists'
import { useLocalStorage } from './hooks/useLocalStorage'
import { MapView } from './components/MapView'
import './styles.css'

type Weather = 'good' | 'okay' | 'bad'
const weatherOptions: Record<Weather, string> = { good: '☀️ 海况优秀', okay: '🌤️ 一般', bad: '🌧️ 不适合远海' }
const defaultWeather: Record<string, Weather> = { '9/10': 'good', '9/11': 'okay', '9/12': 'good' }
const budgetFields = ['餐饮', '榴莲', 'Grab', '出海', '按摩', '购物', '其他']

function SectionHead({ kicker, title, note }: { kicker: string; title: string; note?: string }) { return <div className="section-head"><div><div className="section-kicker">{kicker}</div><h2>{title}</h2></div>{note && <div className="section-note">{note}</div>}</div> }
function ScrollButton({ target, children, icon = true }: { target: string; children: React.ReactNode; icon?: boolean }) { return <button className="ghost-btn small" onClick={() => document.getElementById(target)?.scrollIntoView({ behavior: 'smooth' })}>{children}{icon && <ArrowUpRight size={14} />}</button> }

function Hero() { const status = tripStatus(); return <header className="hero"><div className="hero-content"><div className="eyebrow"><Compass size={15} /> 2026 · FIELD GUIDE · MALAYSIA</div><h1>{trip.title}<br /><em>{trip.subtitle}</em></h1><p>深圳—吉隆坡—亚庇 · 09.07—09.13 · {trip.days}天{trip.nights}晚</p><div className="hero-bottom"><div className="status-pill"><CalendarDays size={15} /> {status.label}</div><div className="route-line">{trip.route.map((stop, i) => <span key={`${stop.code}-${i}`} style={{ display: 'contents' }}><span className="route-dot" /> <span>{stop.code}</span>{i < trip.route.length - 1 && <span className="route-sep" />}</span>)}</div></div></div></header> }

function Overview() { return <section className="section" id="overview"><SectionHead kicker="01 · overview" title="先看一眼全程" note="城市与海岛的节奏，留出午休和天气弹性，不做特种兵。" /><div className="overview-grid"><div className="card route-card">{trip.route.map((stop, i) => <span className="route-stop" key={`${stop.code}-${i}`}><strong>{stop.code}</strong><span>{stop.name}</span>{(i === 1 || i === 2) && <small style={{ display: 'block', color: 'var(--teal)', marginTop: 8 }}>{i === 1 ? '2晚' : '4晚'}</small>}</span>)} </div><div className="card metric-card"><div><div className="metric-label">TWO PEOPLE · FLIGHTS PAID</div><div className="metric">¥6,172</div><div className="metric-sub">两人三段机票总价 · 酒店已支付</div></div><div className="tag-list">{trip.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div></div></div></section> }

function Itinerary() { const [selected, setSelected] = useState(0); const [open, setOpen] = useState<string | null>('d7-1'); const [done, setDone] = useLocalStorage<Record<string, boolean>>('trip-itinerary-done', {}); const day = itinerary[selected]; return <section className="section" id="itinerary"><SectionHead kicker="02 · itinerary" title="每天只看今天" note="点击事项展开详情；完成状态会保存在这台设备上。" /><div className="date-tabs">{itinerary.map((item, i) => <button className={`date-tab ${selected === i ? 'active' : ''}`} onClick={() => setSelected(i)} key={item.date}><strong>{item.date}</strong><span>{item.weekday}</span></button>)}</div><div className="itinerary-layout"><div className="card"><div className="day-heading"><h3>{day.title}</h3><span className="intensity">{day.intensity}</span></div><div className="timeline">{day.items.map(item => { const isOpen = open === item.id; const isDone = Boolean(done[item.id]); return <div className={`timeline-item ${item.tone ?? ''}`} key={item.id}><div className="timeline-main"><div className="time">{item.time}</div><div className={`event ${isOpen ? 'open' : ''}`}><button onClick={() => setOpen(isOpen ? null : item.id)} aria-expanded={isOpen}><div className="event-title"><span>{item.title}</span><ChevronDown size={16} /></div><div className="summary">{item.summary}</div></button>{isOpen && <div className="event-detail">{item.details.map(detail => <div key={detail}>{detail}</div>)}</div>}</div><button className={`complete-btn ${isDone ? 'done' : ''}`} onClick={() => setDone(prev => ({ ...prev, [item.id]: !isDone }))} aria-label={isDone ? '取消完成' : '标记完成'}>{isDone ? <Check size={14} /> : '完成'}</button></div></div> })}</div></div><FlightMini /></div></section> }
function FlightMini() { return <div className="flight-list">{flights.map((flight, index) => <FlightCard flight={flight} key={flight.date} highlight={index === 2} />)}</div> }
function FlightCard({ flight, highlight }: { flight: typeof flights[number]; highlight?: boolean }) { const [open, setOpen] = useState(false); return <div className={`card flight-card ${highlight ? 'highlight-flight' : ''}`}><div className="flight-top"><div><div className="micro">{flight.date} · {flight.route}</div><div className="flight-route"><strong>{flight.from}</strong><span>→</span><strong>{flight.to}</strong></div><div className="flight-times"><strong>{flight.depart}</strong><span className="flight-line" /><strong>{flight.arrive}</strong></div></div><div className="flight-note">{flight.note}<br /><button className="ghost-btn small" onClick={() => setOpen(!open)}>{open ? '收起' : '详情'} <ChevronDown size={13} /></button></div></div>{open && <div className="expand-area">{flight.details.map(detail => <div className="detail-row" key={detail}>{detail}</div>)}</div>}</div> }

function Hotels() { return <section className="section" id="hotels"><SectionHead kicker="03 · stays" title="三段落脚点" note="市区酒店优先安排走路可达的吃喝，换酒店日把行李作为唯一固定事件。" /><div className="hotel-grid">{hotels.map((hotel, i) => <div className={`card hotel-card ${hotel.color}`} key={hotel.name}><div className="dates">{hotel.dates}</div><h3>{hotel.name}</h3>{hotel.address && <div className="hotel-address">{hotel.address}</div>}<div className="tag-list">{hotel.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div><div className="hotel-note">{hotel.note}</div>{i === 0 && <a className="ghost-btn small" style={{ marginTop: 13, textDecoration: 'none' }} href="https://www.google.com/maps/search/?api=1&query=The+FACE+Style+Hotel+Kuala+Lumpur" target="_blank" rel="noreferrer">打开 Google Maps <ExternalLink size={13} /></a>}{i === 2 && <div className="hotel-alert"><strong>9/11 固定换酒店</strong><br />Sheraton 退房 → 全部行李 Grab → Hyatt 寄存</div>}</div>)}</div></section> }

function Planner() { const [weather, setWeather] = useLocalStorage<Record<string, Weather>>('trip-weather', defaultWeather); const [resetKey, setResetKey] = useState(0); const recommendation = useMemo(() => { const days = ['9/10', '9/11', '9/12']; const firstGood = days.find(day => weather[day] === 'good'); const result = days.map(day => ({ day, plan: day === '9/11' ? '换酒店＋休闲＋Api Api' : day === firstGood ? '环滩岛 Mengalum' : weather[day] === 'good' ? 'TARP 双岛' : weather[day] === 'okay' ? 'TARP（视海况）' : '市区休闲 / 按摩 / 榴莲' })); return { result, allBad: days.every(day => weather[day] === 'bad') } }, [weather]); return <section className="section" id="planner"><SectionHead kicker="04 · weather routing" title="亚庇出海排期助手" note="不要伪造未来天气。出发前根据海况重新选择，网站会把最早的好天气留给环滩岛。" /><div className="planner"><div className="card"><div className="weather-grid">{['9/10', '9/11', '9/12'].map(day => <div className="weather-day" key={`${day}-${resetKey}`}><strong>{day}</strong><select className="weather-select" value={weather[day]} onChange={e => setWeather(prev => ({ ...prev, [day]: e.target.value as Weather }))}>{Object.entries(weatherOptions).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>)}</div><div className="weather-option"><span className="micro">优先级：环滩岛 → TARP → 红树林 → 市区</span><button className="ghost-btn small" onClick={() => { setWeather(defaultWeather); setResetKey(key => key + 1) }}><RotateCcw size={13} />恢复默认</button></div></div><div className="recommend"><div className="section-kicker">LIVE RECOMMENDATION</div><h3>根据当前选择，推荐：</h3>{recommendation.result.map(row => <div className="recommend-row" key={row.day}><strong>{row.day}</strong><span>{row.plan}</span></div>)}{recommendation.allBad && <div className="no-go">三天海况都差：不要强行远海，改为市区、按摩、海鲜、榴莲、酒店休息。</div>}</div></div></section> }

function SeaModules() { const [seaDone, setSeaDone] = useLocalStorage<Record<string, boolean>>('trip-sea-checks', {}); const [mangrove, setMangrove] = useLocalStorage('trip-mangrove', false); const [islands, setIslands] = useState<'two' | 'three'>('two'); const items = ['是否正常出海', '酒店接送时间', '集合地点', '码头', '天气取消政策', '是否支持改期', '是否提供浮潜装备', '是否包含午餐']; const sunsetText = useMemo(() => { const now = new Date(); const target = new Date('2026-09-12T18:17:00'); const hours = Math.max(0, Math.floor((target.getTime() - now.getTime()) / 3600000)); const mins = Math.max(0, Math.floor(((target.getTime() - now.getTime()) % 3600000) / 60000)); return now > target ? '日落已过' : `距离日落 ${hours}小时 ${mins}分` }, []); return <section className="section" id="sea"><SectionHead kicker="05 · ocean days" title="两天海岛安排" note="环滩看天气，TARP 默认两岛；9/11 换酒店是不可移动的锚点。" /><div className="special-grid"><div className="special-card ocean"><div className="special-title"><div><h3>环滩岛 Mengalum</h3><p>远海 · 高天气敏感 · 优先抢好天气。若被排期到这天，出发前逐项确认。</p></div><Waves color="var(--teal)" /></div><div className="check-list">{items.map(item => <label className="check-item" key={item}><input type="checkbox" checked={Boolean(seaDone[item])} onChange={() => setSeaDone(prev => ({ ...prev, [item]: !prev[item] }))} />{item}</label>)}</div></div><div className="special-card sunset"><div className="special-title"><div><h3>9/12 · TARP＋日落</h3><p>默认 Sapi＋Manukan。两岛少等待、更轻松，15:30 回市区后留给晚霞。</p></div><span className="status-pill" style={{ color: 'var(--ink)', borderColor: 'var(--line)', background: '#fff8e8' }}>{sunsetText}</span></div><div className="island-compare">{(['two', 'three'] as const).map(type => <button className="island" style={{ border: islands === type ? '2px solid var(--sun)' : '1px solid transparent', textAlign: 'left' }} key={type} onClick={() => setIslands(type)}><strong>{type === 'two' ? '两岛 · 默认推荐' : '三岛 · 对比'}</strong><span>{type === 'two' ? '少换一次船 · 更多浮潜时间 · 更多沙滩时间 · 更轻松' : '行程更满 · 等待更多 · 适合体力充足且海况稳定'}</span></button>)}</div><label className="toggle" style={{ marginTop: 17 }}><input type="checkbox" checked={mangrove} onChange={e => setMangrove(e.target.checked)} />红树林？</label>{mangrove && <div className="event-detail" style={{ marginTop: 10 }}>Klias 等红树林距离亚庇约 100km，通常下午出发 → 看长鼻猴 → 晚餐 → 萤火虫 → 晚上返回。<br /><strong>可舍弃项，不与 TARP 安排在同一天。</strong></div>}</div></div></section> }

function Checklist() { const [checks, setChecks] = useLocalStorage<Record<string, boolean>>('trip-checks', {}); const total = checklistGroups.reduce((sum, group) => sum + group.items.length, 0); const completed = Object.values(checks).filter(Boolean).length; const reset = () => { if (window.confirm('确定重置所有行前清单吗？')) setChecks({}) }; return <section className="section" id="checklist"><SectionHead kicker="06 · ready kit" title="行前准备进度" note="证件、支付、手机、出海、电子、药物和 2026 特殊项，一次收好。" /><div className="card progress-card"><div className="progress-value">{Math.round((completed / total) * 100)}%</div><div className="progress-track"><div className="progress-fill" style={{ width: `${(completed / total) * 100}%` }} /></div><button className="ghost-btn small" onClick={reset}><RotateCcw size={13} />全部重置</button></div><div className="check-layout">{checklistGroups.map(group => <div className="card check-group" key={group.id}><h3><span>{group.icon}</span>{group.label}</h3><div className="check-group-list">{group.items.map(item => { const key = `${group.id}:${item}`; return <label className="list-check" key={key}><input type="checkbox" checked={Boolean(checks[key])} onChange={() => setChecks(prev => ({ ...prev, [key]: !prev[key] }))} />{item}</label> })}</div></div>)}</div></section> }

function Budget() { const [spend, setSpend] = useLocalStorage<Record<string, number>>('trip-budget', {}); const total = Object.values(spend).reduce((a, b) => a + (Number(b) || 0), 0); return <section className="section" id="budget"><SectionHead kicker="07 · money" title="现场预算速查" note="机票 ¥6,172 已支付，酒店已支付不计入现场预算。金额按 RM 记录。" /><div className="budget-layout"><div className="card budget-hero"><h3>现场已记录</h3><div className="budget-amount">RM {total.toLocaleString()}</div><p>人均 RM {Math.round(total / 2).toLocaleString()} · 建议舒适档 RM 3000—3500</p><div className="budget-form">{budgetFields.map(field => <label key={field}>{field}<input inputMode="decimal" type="number" min="0" value={spend[field] ?? ''} onChange={e => setSpend(prev => ({ ...prev, [field]: Number(e.target.value) || 0 }))} placeholder="0" /></label>)}</div><button className="ghost-btn small" style={{ marginTop: 16, color: '#fff', borderColor: 'rgba(255,255,255,.25)', background: 'transparent' }} onClick={() => { if (window.confirm('确定清空预算记录吗？')) setSpend({}) }}><X size={13} />清空预算记录</button></div><div className="card"><div className="micro">QUICK RANGE</div><div className="budget-tiers"><div className="tier"><span>节制舒服</span><strong>RM 2500</strong></div><div className="tier"><span>正常舒适</span><strong>RM 3000—3500</strong></div><div className="tier"><span>吃喝比较爽</span><strong>RM 4000+</strong></div></div><div className="event-detail" style={{ marginTop: 19 }}>刷卡永远选择 <strong>MYR</strong>。不要选 CNY / HKD，避免 DCC 动态货币转换。</div></div></div></section> }

function QuickModules() { const [mdac, setMdac] = useLocalStorage('trip-mdac', false); return <><section className="section" id="quick"><SectionHead kicker="08 · quick access" title="旅行现场工具箱" note="把最容易临时查找的内容放在一起，点开就能用。" /><div className="tool-grid"><a className="card tool-card" href="https://www.google.com/maps" target="_blank" rel="noreferrer"><div className="tool-icon"><Map size={18} /></div><h3>地图导航</h3><p>Leaflet＋OpenStreetMap 标记全程地点，Google Maps 负责导航。</p></a><div className="card tool-card"><div className="tool-icon"><WalletCards size={18} /></div><h3>支付速查</h3><p>酒店押金 Visa；商场 Visa / 支付宝；夜市现金；榴莲现金优先。</p></div><a className="card tool-card" href="https://www.met.gov.my/" target="_blank" rel="noreferrer"><div className="tool-icon"><CloudSun size={18} /></div><h3>天气＆烟霾</h3><p>关注雷暴、风浪、Rough Seas、烟霾。查看 METMalaysia / myCuaca。</p></a><div className="card tool-card"><div className="tool-icon">🍈</div><h3>榴莲攻略</h3><p>西马经典名品，沙巴隐藏角色；购买前确认 RM/kg。</p></div></div><div className="card" style={{ marginTop: 14, padding: 0, overflow: 'hidden' }}><MapView /></div></section><section className="section" id="mdac"><SectionHead kicker="09 · border entry" title="MDAC 入境卡" note="9 月 7 日入境，推荐 9 月 4—6 日填写；填好后截图、PDF、纸质各备一份。" /><div className="card mdac-card"><div><h3>Malaysia Digital Arrival Card</h3><p>填写需要：护照、航班、The FACE 地址、电话、邮箱。<br />9/4 前还没到填写时间；9/4—9/6 现在可以填写；9/7 确认已经填写。</p><a href="https://imigresen-online.imi.gov.my/mdac/main" target="_blank" rel="noreferrer" className="ghost-btn small" style={{ marginTop: 14, textDecoration: 'none' }}>前往官方 MDAC <ExternalLink size={13} /></a></div><div className="mdac-side"><strong>{mdac ? '已完成' : '待完成'}</strong><label className="toggle" style={{ marginTop: 10 }}><input type="checkbox" checked={mdac} onChange={e => setMdac(e.target.checked)} />已完成 MDAC</label></div></div></section><section className="section" id="durian"><SectionHead kicker="10 · durian field notes" title="Durian 🍈" note="价格受到等级、产区、果型、当天供应影响；不要把亚庇只当成猫山王追逐场。" /><div className="durian-grid"><div className="card durian-card"><div className="micro">KUALA LUMPUR · 西马经典名品</div><h3 style={{ margin: '9px 0 0' }}>甜、苦、浓郁的层次局</h3><div className="variety-grid">{[['D24', '甜度中高'], ['红虾', '奶油感'], ['猫山王 D197', '苦甜浓郁'], ['黑刺 D200', '香气复杂']].map(([name, note]) => <div className="variety" key={name}><strong>{name}</strong><span>{note}</span></div>)}</div></div><div className="card durian-card"><div className="micro">KOTA KINABALU · 沙巴隐藏角色</div><h3 style={{ margin: '9px 0 0' }}>不要只追猫山王</h3><div className="tag-list">{['沙巴老树榴莲', 'Tekka', 'Dalit', 'Sukang', '红肉榴莲', '橙肉榴莲'].map(item => <span className="tag" key={item}>{item}</span>)}</div><div className="event-detail" style={{ marginTop: 18 }}>购买前确认 <strong>RM/kg</strong>，称重前先问价。</div></div></div></section></> }

function Safety() { return <section className="section" id="safety"><SectionHead kicker="11 · travel reminders" title="旅行提醒卡" note="不制造恐慌，只记住几个让旅程更舒服的小动作。" /><div className="card safety"><div className="safety-list">{['人多区域注意手机钱包', '手机不要长期靠马路一侧举着', 'Grab 使用官方 APP', '夜间避免偏僻小巷', '出海穿救生衣，海况不好不强行出海', '猴子区域不要拿食物逗猴', '海鲜购买前确认价格', '榴莲称重前确认 RM/kg', '信用卡不要离开视线', '遇罚款要求 official ticket / receipt'].map(item => <p key={item}>{item}</p>)}</div></div></section> }

function App() { useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => undefined) }, []); const [active, setActive] = useState('overview'); const nav = [{ id: 'overview', label: '首页', icon: Compass }, { id: 'itinerary', label: '行程', icon: CalendarDays }, { id: 'checklist', label: '清单', icon: ListChecks }, { id: 'budget', label: '预算', icon: WalletCards }, { id: 'quick', label: '更多', icon: Landmark }]; useEffect(() => { const observer = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id) }, { rootMargin: '-15% 0px -65% 0px', threshold: [0, .25, .5] }); ['overview', 'itinerary', 'checklist', 'budget', 'quick', 'safety'].forEach(id => { const el = document.getElementById(id); if (el) observer.observe(el) }); return () => observer.disconnect() }, []); const go = (id: string) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }; const resetTripData = () => { if (!window.confirm('确定重置所有旅行数据吗？这会清除本机的完成状态、天气排期、预算和 MDAC 状态。')) return; ['trip-itinerary-done', 'trip-weather', 'trip-sea-checks', 'trip-mangrove', 'trip-checks', 'trip-budget', 'trip-mdac'].forEach(key => localStorage.removeItem(key)); window.location.reload() }; return <div className="app"><div className="container"><div className="topbar"><div className="brand"><div className="brand-mark">✦</div><div>Travel dossier <span>for two</span></div></div><div className="top-actions"><ScrollButton target="mdac">MDAC</ScrollButton><button className="icon-btn" title="查看提醒" onClick={() => go('safety')}><ShieldCheck size={17} /></button><button className="ghost-btn small" onClick={resetTripData}><RotateCcw size={13} />重置数据</button></div></div><Hero /><Overview /><Itinerary /><Hotels /><Planner /><SeaModules /><Checklist /><Budget /><QuickModules /><Safety /><footer className="footer">Malaysia 2026 · 深圳—吉隆坡—亚庇<br />数据与状态都保存在本机浏览器；天气、海况、航班请在出发前再次确认。</footer></div><nav className="bottom-nav" aria-label="主导航">{nav.map(({ id, label, icon: Icon }) => <button className={active === id ? 'active' : ''} key={id} onClick={() => go(id)}><Icon size={17} />{label}</button>)}</nav></div> }

export default App

type TripWindow = Window & { __malaysiaTripRoot?: ReturnType<typeof createRoot> }
const tripWindow = window as TripWindow
const root = tripWindow.__malaysiaTripRoot ?? createRoot(document.getElementById('root')!)
tripWindow.__malaysiaTripRoot = root
root.render(<App />)


